### ISSUE TITLE
Automatically run tests in gitlab actions CI/CD

### ISSUE THREAD

**Issue by iokiwi** [tgenv/tgenv#11]
We ought to get tests running as a safety net to ensure that pull requests we accepts don't cause weird regressions.

There are already tests included in the repo, but running them locally failed

We should get them working and then make them in gitlab actions on merge requests as a gate before merging.

**Comment by weyderfs** [comment]
@iokiwi a big thanks again.

I have been talking with @Fabianoshz about improvements at last week, and now include tests it's a big goal.
