### ISSUE TITLE
Fix or disable tests for test-main-pushes action.

### ISSUE THREAD

**Issue by iokiwi** [tgenv/tgenv#13]
Tests for windows failed after merging. We should disable them or get them working.

 * https://github.com/tgenv/tgenv/actions/runs/3929313007

Tests for windows weren't run on the pull request to add tests. If we get them working, we should also run them on pull requests.

I haven't had a close look at why they failed but I am wondering about the effort/value tradeoff of fixing vs disabling.

Currently our readme has a tests failed badge which isn't a good look so also wonder if we should do something about that in the meantime.

**Comment by iokiwi** [comment]
Actually I think part of the problem is resolved by https://github.com/cunymatthieu/tgenv/pull/43

We should revisit it.

**Comment by weyderfs** [comment]
I've tried fix de Windows installation in the past, but without success in this [_pull-request_](https://github.com/tgenv/tgenv/pull/4). Maybe I can failed miserably in the tests in the Windows 10. 🤣

**Comment by iokiwi** [comment]
Yeah, I think there needs to be some logic around unzipping and maybe PATH setting for windows. 

I'm not super enthused to go down that rabbit hole hence my comments about having a think about the value/effort of fixing vs  just disable the test and not really supporting it for now.

On Windows there are still other options including running it in docker or WSL as I do on my work machine and it works fine.

My preference would be to disable the tests for windows as there is no point testing something works that we know doesn't work.

If/when we properly support windows installs we can reinstate the tests.

**Comment by weyderfs** [comment]
@iokiwi For me we can disable for now the Windows support in the future we can pick up again. Maybe someone Windows lover can come to help.
