### ISSUE TITLE
[BUG] ibexec/tgenv-upgrade: Permission denied

### ISSUE THREAD

**Issue by weyderfs** [tgenv/tgenv#23]
# TL &DR

Suchlike the @iokiwi advise me the permissions to execute the script of upgrade not work.... 😂 

### Alpine Container

```
/teste/tgenv/libexec # ./tgenv-upgrade 
sh: ./tgenv-upgrade: Permission denied

```
### In my laptop Ubuntu after done a 'git pull master` to get the merge of #17 .

```
$ $HOME/$USER/.tgenv/libexec/tgenv-upgrade: Permission denied
```

So I'm looking for solution, anyway this bug don't impact other functionalities of the TGEnv.

**Comment by weyderfs** [comment]
I have been thinking about how to fix it, my suggestion would be create a installation script where the permissions it was set there.

**Comment by iokiwi** [comment]
Yep git remembers file permissions. Handy. I've reviewed and approved your fix. Feel free to merge and close issue

**Comment by weyderfs** [comment]
merged. tks
