### ISSUE TITLE
Windows installation doesn't work. The download URL should contain .exe

### ISSUE THREAD

**Issue by ssemichev** [tgenv/tgenv#33]
tgenv install 0.50.14
[INFO] Installing Terragrunt v0.50.14
[INFO] Downloading release tarball from https://github.com/gruntwork-io/terragrunt/releases/download/v0.50.14/terragrunt_windows_amd64
curl: (22) The requested URL returned error: 404

tgenv: tgenv-install: [ERROR] Tarball download failed

The correct URL is https://github.com/gruntwork-io/terragrunt/releases/download/v0.50.14/terragrunt_windows_amd64.exe

**Comment by weyderfs** [comment]
@ssemichev actually TGenv doesn't supports Windows native installation because the maintainers use Mac or Linux. I think so in WSL2 you are able to install the linux version.
