### ISSUE TITLE
Detect Terragrunt Versions By Release

### ISSUE THREAD

**Issue by yhakbar** [tgenv/tgenv#34]
The Gruntwork team is updating our release process to rely on pre-releases as a way to avoid users trying to utilize new releases before binaries are successfully compiled and uploaded to them.

In order for `tgenv` users to benefit from this, available versions should be determined using releases, rather than tags, and a default filter should prevent pre-releases from showing up as an available version.

This would be achieved by adjusting the logic in:
https://github.com/tgenv/tgenv/blob/main/libexec/tgenv-list-remote

To leverage the following endpoint:
https://api.github.com/repos/gruntwork-io/terragrunt/releases

Would the maintainers here be amenable to that?

**Comment by weyderfs** [comment]
Hi @yhakbar, thanks for share your question, but I believe that is not our philosophy of using TGenv. Our idea is that you can use the version you want, you as a user need to understand which version you want to use, whether it is an LTS or not.
