### ISSUE TITLE
[BUG] Command tgenv upgrade not working propertly 

### ISSUE THREAD

**Issue by weyderfs** [tgenv/tgenv#40]
# TL & DR

## From any path at terminal shell
```sh
$ tgenv upgrade
fatal: not a git repository (or any of the parent directories): .git
```
## From inside TGEnv directory
```sh
$ tgenv upgrade
fatal: cannot change to '* master': No such file or directory
```

## Upgrade source file
- [/libexec/tgenv-upgrade](https://github.com/tgenv/tgenv/blob/main/libexec/tgenv-upgrade)

**Comment by iokiwi** [comment]
I think we have the main branch. But yes that script has several issues. I resisted refactoring it but I think it can be much simpler.

Also, consider that command only makes sense if the user installed it using the bash method but if we get a homebrew formula working we will need to consider how we support that
